"""add platform integration connection table

Revision ID: 09bcf2ae696a
Revises: 40ad2f77a13c
Create Date: 2026-07-26 22:35:08.213327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09bcf2ae696a"
down_revision: str | Sequence[str] | None = "40ad2f77a13c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_integration_connections",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("connected_by_platform_user_id", sa.UUID(), nullable=True),
        sa.Column("external_account_id", sa.String(length=255), nullable=True),
        sa.Column("external_account_email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=True),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'needs_reconnect', 'revoked', 'error')",
            name=op.f("ck_platform_integration_connections_status_valid"),
        ),
        sa.CheckConstraint(
            "external_account_email IS NULL OR external_account_email = lower(external_account_email)",
            name=op.f(
                "ck_platform_integration_connections_external_account_email_lowercase"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["connected_by_platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_integration_connections_connected_by_user_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["platform_integration_providers.id"],
            name="fk_platform_integration_connections_provider_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_integration_connections")),
    )
    op.create_index(
        "ix_platform_integration_connections_connected_by_user_id",
        "platform_integration_connections",
        ["connected_by_platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_integration_connections_external_account_email",
        "platform_integration_connections",
        ["external_account_email"],
        unique=False,
    )
    op.create_index(
        "ix_platform_integration_connections_provider_id",
        "platform_integration_connections",
        ["provider_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_integration_connections_status",
        "platform_integration_connections",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_platform_integration_connections_token_expires_at",
        "platform_integration_connections",
        ["token_expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_platform_integration_connections_provider_external_account",
        "platform_integration_connections",
        ["provider_id", "external_account_id"],
        unique=True,
        postgresql_where=sa.text(
            "external_account_id IS NOT NULL AND deleted_at IS NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_platform_integration_connections_provider_external_account",
        table_name="platform_integration_connections",
        postgresql_where=sa.text(
            "external_account_id IS NOT NULL AND deleted_at IS NULL"
        ),
    )
    op.drop_index(
        "ix_platform_integration_connections_token_expires_at",
        table_name="platform_integration_connections",
    )
    op.drop_index(
        "ix_platform_integration_connections_status",
        table_name="platform_integration_connections",
    )
    op.drop_index(
        "ix_platform_integration_connections_provider_id",
        table_name="platform_integration_connections",
    )
    op.drop_index(
        "ix_platform_integration_connections_external_account_email",
        table_name="platform_integration_connections",
    )
    op.drop_index(
        "ix_platform_integration_connections_connected_by_user_id",
        table_name="platform_integration_connections",
    )
    op.drop_table("platform_integration_connections")
    # ### end Alembic commands ###
