"""create module catalog table

Revision ID: 33eed5ca0481
Revises: 5e780c06c869
Create Date: 2026-07-26 17:41:20.058275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33eed5ca0481"
down_revision: str | Sequence[str] | None = "5e780c06c869"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("module_group", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "is_plan_assignable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "is_add_on", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "module_group IN ('platform', 'tenant')",
            name=op.f("ck_modules_module_group_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'deprecated', 'coming_soon')",
            name=op.f("ck_modules_status_valid"),
        ),
        sa.CheckConstraint("key = lower(key)", name=op.f("ck_modules_key_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("key", name="uq_modules_key"),
    )
    op.create_index("ix_modules_is_add_on", "modules", ["is_add_on"], unique=False)
    op.create_index(
        "ix_modules_is_plan_assignable", "modules", ["is_plan_assignable"], unique=False
    )
    op.create_index(
        "ix_modules_module_group", "modules", ["module_group"], unique=False
    )
    op.create_index("ix_modules_status", "modules", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_modules_status", table_name="modules")
    op.drop_index("ix_modules_module_group", table_name="modules")
    op.drop_index("ix_modules_is_plan_assignable", table_name="modules")
    op.drop_index("ix_modules_is_add_on", table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
