"""create subscription plan and add-on tables

Revision ID: 3b7fed4325de
Revises: 33eed5ca0481
Create Date: 2026-07-26 17:58:25.863608

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b7fed4325de"
down_revision: str | Sequence[str] | None = "33eed5ca0481"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "add_ons",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("billing_interval", sa.String(length=32), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "billing_interval IN ('monthly', 'yearly', 'one_time')",
            name=op.f("ck_add_ons_billing_interval_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'archived')",
            name=op.f("ck_add_ons_status_valid"),
        ),
        sa.CheckConstraint(
            "currency = upper(currency)", name=op.f("ck_add_ons_currency_uppercase")
        ),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_add_ons_currency_length_valid")
        ),
        sa.CheckConstraint(
            "price_amount >= 0", name=op.f("ck_add_ons_price_amount_non_negative")
        ),
        sa.CheckConstraint(
            "slug = lower(slug)", name=op.f("ck_add_ons_slug_lowercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_add_ons")),
        sa.UniqueConstraint("slug", name="uq_add_ons_slug"),
    )
    op.create_index(
        "ix_add_ons_billing_interval", "add_ons", ["billing_interval"], unique=False
    )
    op.create_index("ix_add_ons_status", "add_ons", ["status"], unique=False)
    op.create_table(
        "subscription_plans",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("billing_interval", sa.String(length=32), nullable=False),
        sa.Column("price_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "trial_days", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "billing_interval IN ('monthly', 'yearly', 'one_time')",
            name=op.f("ck_subscription_plans_billing_interval_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'archived')",
            name=op.f("ck_subscription_plans_status_valid"),
        ),
        sa.CheckConstraint(
            "currency = upper(currency)",
            name=op.f("ck_subscription_plans_currency_uppercase"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3",
            name=op.f("ck_subscription_plans_currency_length_valid"),
        ),
        sa.CheckConstraint(
            "price_amount >= 0",
            name=op.f("ck_subscription_plans_price_amount_non_negative"),
        ),
        sa.CheckConstraint(
            "slug = lower(slug)", name=op.f("ck_subscription_plans_slug_lowercase")
        ),
        sa.CheckConstraint(
            "trial_days >= 0",
            name=op.f("ck_subscription_plans_trial_days_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
        sa.UniqueConstraint("slug", name="uq_subscription_plans_slug"),
    )
    op.create_index(
        "ix_subscription_plans_billing_interval",
        "subscription_plans",
        ["billing_interval"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_plans_status", "subscription_plans", ["status"], unique=False
    )
    op.create_table(
        "add_on_modules",
        sa.Column("add_on_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["add_on_id"],
            ["add_ons.id"],
            name="fk_add_on_modules_add_on_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name="fk_add_on_modules_module_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_add_on_modules")),
        sa.UniqueConstraint(
            "add_on_id", "module_id", name="uq_add_on_modules_add_on_module"
        ),
    )
    op.create_index(
        "ix_add_on_modules_add_on_id", "add_on_modules", ["add_on_id"], unique=False
    )
    op.create_index(
        "ix_add_on_modules_module_id", "add_on_modules", ["module_id"], unique=False
    )
    op.create_table(
        "subscription_plan_limits",
        sa.Column("subscription_plan_id", sa.UUID(), nullable=False),
        sa.Column("limit_key", sa.String(length=80), nullable=False),
        sa.Column("limit_value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "limit_key IN ('max_team_members', 'max_storage_mb', 'max_custom_roles')",
            name=op.f("ck_subscription_plan_limits_limit_key_valid"),
        ),
        sa.CheckConstraint(
            "limit_value >= 0",
            name=op.f("ck_subscription_plan_limits_limit_value_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
            name="fk_subscription_plan_limits_plan_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plan_limits")),
        sa.UniqueConstraint(
            "subscription_plan_id",
            "limit_key",
            name="uq_subscription_plan_limits_plan_key",
        ),
    )
    op.create_index(
        "ix_subscription_plan_limits_limit_key",
        "subscription_plan_limits",
        ["limit_key"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_plan_limits_subscription_plan_id",
        "subscription_plan_limits",
        ["subscription_plan_id"],
        unique=False,
    )
    op.create_table(
        "subscription_plan_modules",
        sa.Column("subscription_plan_id", sa.UUID(), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name="fk_subscription_plan_modules_module_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
            name="fk_subscription_plan_modules_plan_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plan_modules")),
        sa.UniqueConstraint(
            "subscription_plan_id",
            "module_id",
            name="uq_subscription_plan_modules_plan_module",
        ),
    )
    op.create_index(
        "ix_subscription_plan_modules_module_id",
        "subscription_plan_modules",
        ["module_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_plan_modules_subscription_plan_id",
        "subscription_plan_modules",
        ["subscription_plan_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_subscription_plan_modules_subscription_plan_id",
        table_name="subscription_plan_modules",
    )
    op.drop_index(
        "ix_subscription_plan_modules_module_id", table_name="subscription_plan_modules"
    )
    op.drop_table("subscription_plan_modules")
    op.drop_index(
        "ix_subscription_plan_limits_subscription_plan_id",
        table_name="subscription_plan_limits",
    )
    op.drop_index(
        "ix_subscription_plan_limits_limit_key", table_name="subscription_plan_limits"
    )
    op.drop_table("subscription_plan_limits")
    op.drop_index("ix_add_on_modules_module_id", table_name="add_on_modules")
    op.drop_index("ix_add_on_modules_add_on_id", table_name="add_on_modules")
    op.drop_table("add_on_modules")
    op.drop_index("ix_subscription_plans_status", table_name="subscription_plans")
    op.drop_index(
        "ix_subscription_plans_billing_interval", table_name="subscription_plans"
    )
    op.drop_table("subscription_plans")
    op.drop_index("ix_add_ons_status", table_name="add_ons")
    op.drop_index("ix_add_ons_billing_interval", table_name="add_ons")
    op.drop_table("add_ons")
    # ### end Alembic commands ###
