"""add platform user invitation tables

Revision ID: 40ad2f77a13c
Revises: e7e80fdfbfde
Create Date: 2026-07-26 22:17:06.119724

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40ad2f77a13c"
down_revision: str | Sequence[str] | None = "e7e80fdfbfde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_user_invitations",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("invited_by_platform_user_id", sa.UUID(), nullable=True),
        sa.Column("accepted_platform_user_id", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'expired', 'revoked')",
            name=op.f("ck_platform_user_invitations_status_valid"),
        ),
        sa.CheckConstraint(
            "email = lower(email)",
            name=op.f("ck_platform_user_invitations_email_lowercase"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_user_invitations_accepted_platform_user_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_user_invitations_invited_by_platform_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_user_invitations")),
        sa.UniqueConstraint(
            "token_hash", name="uq_platform_user_invitations_token_hash"
        ),
    )
    op.create_index(
        "ix_platform_user_invitations_accepted_platform_user_id",
        "platform_user_invitations",
        ["accepted_platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_invitations_email",
        "platform_user_invitations",
        ["email"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_invitations_expires_at",
        "platform_user_invitations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_invitations_invited_by_platform_user_id",
        "platform_user_invitations",
        ["invited_by_platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_invitations_status",
        "platform_user_invitations",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_platform_user_invitations_one_pending_per_email",
        "platform_user_invitations",
        ["email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "platform_user_invitation_roles",
        sa.Column("platform_user_invitation_id", sa.UUID(), nullable=False),
        sa.Column("platform_role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_role_id"],
            ["platform_roles.id"],
            name="fk_platform_user_invitation_roles_role_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_invitation_id"],
            ["platform_user_invitations.id"],
            name="fk_platform_user_invitation_roles_invitation_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_user_invitation_roles")),
        sa.UniqueConstraint(
            "platform_user_invitation_id",
            "platform_role_id",
            name="uq_platform_user_invitation_roles_invitation_role",
        ),
    )
    op.create_index(
        "ix_platform_user_invitation_roles_invitation_id",
        "platform_user_invitation_roles",
        ["platform_user_invitation_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_invitation_roles_role_id",
        "platform_user_invitation_roles",
        ["platform_role_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_platform_user_invitation_roles_role_id",
        table_name="platform_user_invitation_roles",
    )
    op.drop_index(
        "ix_platform_user_invitation_roles_invitation_id",
        table_name="platform_user_invitation_roles",
    )
    op.drop_table("platform_user_invitation_roles")
    op.drop_index(
        "uq_platform_user_invitations_one_pending_per_email",
        table_name="platform_user_invitations",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        "ix_platform_user_invitations_status", table_name="platform_user_invitations"
    )
    op.drop_index(
        "ix_platform_user_invitations_invited_by_platform_user_id",
        table_name="platform_user_invitations",
    )
    op.drop_index(
        "ix_platform_user_invitations_expires_at",
        table_name="platform_user_invitations",
    )
    op.drop_index(
        "ix_platform_user_invitations_email", table_name="platform_user_invitations"
    )
    op.drop_index(
        "ix_platform_user_invitations_accepted_platform_user_id",
        table_name="platform_user_invitations",
    )
    op.drop_table("platform_user_invitations")
    # ### end Alembic commands ###
