"""create platform admin rbac tables

Revision ID: 47d5622504b3
Revises: 9b8659769fb8
Create Date: 2026-07-26 15:11:27.898256

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47d5622504b3"
down_revision: str | Sequence[str] | None = "9b8659769fb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_permissions",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key = lower(key)",
            name=op.f("ck_platform_permissions_platform_permissions_key_lowercase"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_permissions")),
        sa.UniqueConstraint("key", name="uq_platform_permissions_key"),
    )
    op.create_index(
        "ix_platform_permissions_category",
        "platform_permissions",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_platform_permissions_key", "platform_permissions", ["key"], unique=False
    )
    op.create_table(
        "platform_roles",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slug = lower(slug)",
            name=op.f("ck_platform_roles_platform_roles_slug_lowercase"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_roles")),
        sa.UniqueConstraint("slug", name="uq_platform_roles_slug"),
    )
    op.create_index("ix_platform_roles_slug", "platform_roles", ["slug"], unique=False)
    op.create_table(
        "platform_users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "is_super_admin",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'suspended', 'locked')",
            name=op.f("ck_platform_users_platform_users_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_users")),
        sa.UniqueConstraint("email", name="uq_platform_users_email"),
    )
    op.create_index(
        "ix_platform_users_email", "platform_users", ["email"], unique=False
    )
    op.create_index(
        "ix_platform_users_status", "platform_users", ["status"], unique=False
    )
    op.create_table(
        "platform_role_permissions",
        sa.Column("platform_role_id", sa.UUID(), nullable=False),
        sa.Column("platform_permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_permission_id"],
            ["platform_permissions.id"],
            name=op.f(
                "fk_platform_role_permissions_platform_permission_id_platform_permissions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["platform_role_id"],
            ["platform_roles.id"],
            name=op.f("fk_platform_role_permissions_platform_role_id_platform_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_role_permissions")),
        sa.UniqueConstraint(
            "platform_role_id",
            "platform_permission_id",
            name="uq_platform_role_permissions_role_permission",
        ),
    )
    op.create_index(
        "ix_platform_role_permissions_platform_permission_id",
        "platform_role_permissions",
        ["platform_permission_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_role_permissions_platform_role_id",
        "platform_role_permissions",
        ["platform_role_id"],
        unique=False,
    )
    op.create_table(
        "platform_user_roles",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("platform_role_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_role_id"],
            ["platform_roles.id"],
            name=op.f("fk_platform_user_roles_platform_role_id_platform_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name=op.f("fk_platform_user_roles_platform_user_id_platform_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_user_roles")),
        sa.UniqueConstraint(
            "platform_user_id",
            "platform_role_id",
            name="uq_platform_user_roles_user_role",
        ),
    )
    op.create_index(
        "ix_platform_user_roles_platform_role_id",
        "platform_user_roles",
        ["platform_role_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_roles_platform_user_id",
        "platform_user_roles",
        ["platform_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_platform_user_roles_platform_user_id", table_name="platform_user_roles"
    )
    op.drop_index(
        "ix_platform_user_roles_platform_role_id", table_name="platform_user_roles"
    )
    op.drop_table("platform_user_roles")
    op.drop_index(
        "ix_platform_role_permissions_platform_role_id",
        table_name="platform_role_permissions",
    )
    op.drop_index(
        "ix_platform_role_permissions_platform_permission_id",
        table_name="platform_role_permissions",
    )
    op.drop_table("platform_role_permissions")
    op.drop_index("ix_platform_users_status", table_name="platform_users")
    op.drop_index("ix_platform_users_email", table_name="platform_users")
    op.drop_table("platform_users")
    op.drop_index("ix_platform_roles_slug", table_name="platform_roles")
    op.drop_table("platform_roles")
    op.drop_index("ix_platform_permissions_key", table_name="platform_permissions")
    op.drop_index("ix_platform_permissions_category", table_name="platform_permissions")
    op.drop_table("platform_permissions")
    # ### end Alembic commands ###
