"""create platform configuration tables

Revision ID: 5e780c06c869
Revises: 0197d803d80f
Create Date: 2026-07-26 17:21:40.032852

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e780c06c869"
down_revision: str | Sequence[str] | None = "0197d803d80f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_integration_providers",
        sa.Column("provider_key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "category IN ('oauth', 'payment', 'email', 'sms', 'storage', 'calendar', 'maps')",
            name=op.f("ck_platform_integration_providers_category_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive')",
            name=op.f("ck_platform_integration_providers_status_valid"),
        ),
        sa.CheckConstraint(
            "provider_key = lower(provider_key)",
            name=op.f("ck_platform_integration_providers_provider_key_lowercase"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_integration_providers")),
        sa.UniqueConstraint(
            "provider_key", name="uq_platform_integration_providers_key"
        ),
    )
    op.create_index(
        "ix_platform_integration_providers_category",
        "platform_integration_providers",
        ["category"],
        unique=False,
    )
    op.create_index(
        "ix_platform_integration_providers_status",
        "platform_integration_providers",
        ["status"],
        unique=False,
    )
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "is_sensitive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "value_type IN ('string', 'boolean', 'number', 'json')",
            name=op.f("ck_platform_settings_value_type_valid"),
        ),
        sa.CheckConstraint(
            "key = lower(key)", name=op.f("ck_platform_settings_key_lowercase")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_settings")),
        sa.UniqueConstraint("key", name="uq_platform_settings_key"),
    )
    op.create_index(
        "ix_platform_settings_is_sensitive",
        "platform_settings",
        ["is_sensitive"],
        unique=False,
    )
    op.create_index(
        "ix_platform_settings_value_type",
        "platform_settings",
        ["value_type"],
        unique=False,
    )
    op.create_table(
        "platform_oauth_configs",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("client_secret_encrypted", sa.Text(), nullable=True),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column(
            "scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'needs_setup'"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'needs_setup')",
            name=op.f("ck_platform_oauth_configs_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["platform_integration_providers.id"],
            name="fk_platform_oauth_configs_provider_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_oauth_configs")),
        sa.UniqueConstraint(
            "provider_id", name="uq_platform_oauth_configs_provider_id"
        ),
    )
    op.create_index(
        "ix_platform_oauth_configs_status",
        "platform_oauth_configs",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_platform_oauth_configs_status", table_name="platform_oauth_configs"
    )
    op.drop_table("platform_oauth_configs")
    op.drop_index("ix_platform_settings_value_type", table_name="platform_settings")
    op.drop_index("ix_platform_settings_is_sensitive", table_name="platform_settings")
    op.drop_table("platform_settings")
    op.drop_index(
        "ix_platform_integration_providers_status",
        table_name="platform_integration_providers",
    )
    op.drop_index(
        "ix_platform_integration_providers_category",
        table_name="platform_integration_providers",
    )
    op.drop_table("platform_integration_providers")
    # ### end Alembic commands ###
