"""add platform configuration table

Revision ID: 715425f0a74d
Revises: 09bcf2ae696a
Create Date: 2026-07-26 22:52:38.519328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "715425f0a74d"
down_revision: str | Sequence[str] | None = "09bcf2ae696a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_configurations",
        sa.Column("config_type", sa.String(length=40), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("integration_connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'needs_setup'"),
            nullable=False,
        ),
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_sensitive",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "config_type IN ('email', 'calendar', 'payment', 'notification', 'security', 'storage', 'maps', 'general')",
            name=op.f("ck_platform_configurations_config_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'inactive', 'needs_setup', 'error')",
            name=op.f("ck_platform_configurations_status_valid"),
        ),
        sa.CheckConstraint(
            "key = lower(key)", name=op.f("ck_platform_configurations_key_lowercase")
        ),
        sa.ForeignKeyConstraint(
            ["integration_connection_id"],
            ["platform_integration_connections.id"],
            name="fk_platform_configurations_integration_connection_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_configurations")),
    )
    op.create_index(
        "ix_platform_configurations_config_type",
        "platform_configurations",
        ["config_type"],
        unique=False,
    )
    op.create_index(
        "ix_platform_configurations_integration_connection_id",
        "platform_configurations",
        ["integration_connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_configurations_is_default",
        "platform_configurations",
        ["is_default"],
        unique=False,
    )
    op.create_index(
        "ix_platform_configurations_is_sensitive",
        "platform_configurations",
        ["is_sensitive"],
        unique=False,
    )
    op.create_index(
        "ix_platform_configurations_key",
        "platform_configurations",
        ["key"],
        unique=False,
    )
    op.create_index(
        "ix_platform_configurations_status",
        "platform_configurations",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_platform_configurations_one_active_default_per_type",
        "platform_configurations",
        ["config_type"],
        unique=True,
        postgresql_where=sa.text(
            "is_default = true AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.create_index(
        "uq_platform_configurations_type_key_active",
        "platform_configurations",
        ["config_type", "key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_platform_configurations_type_key_active",
        table_name="platform_configurations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_platform_configurations_one_active_default_per_type",
        table_name="platform_configurations",
        postgresql_where=sa.text(
            "is_default = true AND status = 'active' AND deleted_at IS NULL"
        ),
    )
    op.drop_index(
        "ix_platform_configurations_status", table_name="platform_configurations"
    )
    op.drop_index(
        "ix_platform_configurations_key", table_name="platform_configurations"
    )
    op.drop_index(
        "ix_platform_configurations_is_sensitive", table_name="platform_configurations"
    )
    op.drop_index(
        "ix_platform_configurations_is_default", table_name="platform_configurations"
    )
    op.drop_index(
        "ix_platform_configurations_integration_connection_id",
        table_name="platform_configurations",
    )
    op.drop_index(
        "ix_platform_configurations_config_type", table_name="platform_configurations"
    )
    op.drop_table("platform_configurations")
    # ### end Alembic commands ###
