"""create company subscription assignment tables

Revision ID: dae7048eb4d5
Revises: 3b7fed4325de
Create Date: 2026-07-26 18:22:56.164493

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dae7048eb4d5"
down_revision: str | Sequence[str] | None = "3b7fed4325de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_add_ons",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("add_on_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "current_period_starts_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("current_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'cancelled', 'expired', 'suspended')",
            name=op.f("ck_company_add_ons_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["add_on_id"],
            ["add_ons.id"],
            name="fk_company_add_ons_add_on_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_company_add_ons_company_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_add_ons")),
    )
    op.create_index(
        "ix_company_add_ons_add_on_id", "company_add_ons", ["add_on_id"], unique=False
    )
    op.create_index(
        "ix_company_add_ons_company_id", "company_add_ons", ["company_id"], unique=False
    )
    op.create_index(
        "ix_company_add_ons_status", "company_add_ons", ["status"], unique=False
    )
    op.create_index(
        "uq_company_add_ons_one_active_per_company_add_on",
        "company_add_ons",
        ["company_id", "add_on_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "company_subscriptions",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("subscription_plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "current_period_starts_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("current_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('trialing', 'active', 'past_due', 'cancelled', 'expired', 'suspended')",
            name=op.f("ck_company_subscriptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name="fk_company_subscriptions_company_id",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_plan_id"],
            ["subscription_plans.id"],
            name="fk_company_subscriptions_plan_id",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_subscriptions")),
    )
    op.create_index(
        "ix_company_subscriptions_company_id",
        "company_subscriptions",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        "ix_company_subscriptions_status",
        "company_subscriptions",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_company_subscriptions_subscription_plan_id",
        "company_subscriptions",
        ["subscription_plan_id"],
        unique=False,
    )
    op.create_index(
        "uq_company_subscriptions_one_active_per_company",
        "company_subscriptions",
        ["company_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('trialing', 'active')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_company_subscriptions_one_active_per_company",
        table_name="company_subscriptions",
        postgresql_where=sa.text("status IN ('trialing', 'active')"),
    )
    op.drop_index(
        "ix_company_subscriptions_subscription_plan_id",
        table_name="company_subscriptions",
    )
    op.drop_index("ix_company_subscriptions_status", table_name="company_subscriptions")
    op.drop_index(
        "ix_company_subscriptions_company_id", table_name="company_subscriptions"
    )
    op.drop_table("company_subscriptions")
    op.drop_index(
        "uq_company_add_ons_one_active_per_company_add_on",
        table_name="company_add_ons",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_company_add_ons_status", table_name="company_add_ons")
    op.drop_index("ix_company_add_ons_company_id", table_name="company_add_ons")
    op.drop_index("ix_company_add_ons_add_on_id", table_name="company_add_ons")
    op.drop_table("company_add_ons")
    # ### end Alembic commands ###
