"""add platform auth session and token tables

Revision ID: e7e80fdfbfde
Revises: 08f0eba3fa3b
Create Date: 2026-07-26 21:54:33.752457

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7e80fdfbfde"
down_revision: str | Sequence[str] | None = "08f0eba3fa3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_auth_events",
        sa.Column("platform_user_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('login_success', 'login_failed', 'logout', 'session_revoked', 'refresh_token_rotated', 'password_reset_requested', 'password_reset_completed', 'email_verification_requested', 'email_verified')",
            name=op.f("ck_platform_auth_events_event_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_auth_events_platform_user_id",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_auth_events")),
    )
    op.create_index(
        "ix_platform_auth_events_created_at",
        "platform_auth_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_auth_events_event_type",
        "platform_auth_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_platform_auth_events_platform_user_id",
        "platform_auth_events",
        ["platform_user_id"],
        unique=False,
    )
    op.create_table(
        "platform_email_verification_tokens",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_email_verification_tokens_platform_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_platform_email_verification_tokens")
        ),
        sa.UniqueConstraint(
            "token_hash", name="uq_platform_email_verification_tokens_token_hash"
        ),
    )
    op.create_index(
        "ix_platform_email_verification_tokens_expires_at",
        "platform_email_verification_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_email_verification_tokens_platform_user_id",
        "platform_email_verification_tokens",
        ["platform_user_id"],
        unique=False,
    )
    op.create_table(
        "platform_password_reset_tokens",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_password_reset_tokens_platform_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_password_reset_tokens")),
        sa.UniqueConstraint(
            "token_hash", name="uq_platform_password_reset_tokens_token_hash"
        ),
    )
    op.create_index(
        "ix_platform_password_reset_tokens_expires_at",
        "platform_password_reset_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_password_reset_tokens_platform_user_id",
        "platform_password_reset_tokens",
        ["platform_user_id"],
        unique=False,
    )
    op.create_table(
        "platform_user_sessions",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=255), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')",
            name=op.f("ck_platform_user_sessions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_user_sessions_platform_user_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_user_sessions")),
        sa.UniqueConstraint(
            "platform_user_id",
            "id",
            name="uq_platform_user_sessions_platform_user_id_id",
        ),
        sa.UniqueConstraint(
            "session_token_hash", name="uq_platform_user_sessions_session_token_hash"
        ),
    )
    op.create_index(
        "ix_platform_user_sessions_expires_at",
        "platform_user_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_sessions_platform_user_id",
        "platform_user_sessions",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_user_sessions_status",
        "platform_user_sessions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "platform_refresh_tokens",
        sa.Column("platform_user_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired', 'rotated')",
            name=op.f("ck_platform_refresh_tokens_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id"],
            ["platform_users.id"],
            name="fk_platform_refresh_tokens_platform_user_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["platform_user_id", "session_id"],
            ["platform_user_sessions.platform_user_id", "platform_user_sessions.id"],
            name="fk_platform_refresh_tokens_platform_user_session",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name="uq_platform_refresh_tokens_token_hash"),
    )
    op.create_index(
        "ix_platform_refresh_tokens_expires_at",
        "platform_refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_platform_refresh_tokens_platform_user_id",
        "platform_refresh_tokens",
        ["platform_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_refresh_tokens_session_id",
        "platform_refresh_tokens",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_platform_refresh_tokens_status",
        "platform_refresh_tokens",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_platform_refresh_tokens_status", table_name="platform_refresh_tokens"
    )
    op.drop_index(
        "ix_platform_refresh_tokens_session_id", table_name="platform_refresh_tokens"
    )
    op.drop_index(
        "ix_platform_refresh_tokens_platform_user_id",
        table_name="platform_refresh_tokens",
    )
    op.drop_index(
        "ix_platform_refresh_tokens_expires_at", table_name="platform_refresh_tokens"
    )
    op.drop_table("platform_refresh_tokens")
    op.drop_index(
        "ix_platform_user_sessions_status", table_name="platform_user_sessions"
    )
    op.drop_index(
        "ix_platform_user_sessions_platform_user_id",
        table_name="platform_user_sessions",
    )
    op.drop_index(
        "ix_platform_user_sessions_expires_at", table_name="platform_user_sessions"
    )
    op.drop_table("platform_user_sessions")
    op.drop_index(
        "ix_platform_password_reset_tokens_platform_user_id",
        table_name="platform_password_reset_tokens",
    )
    op.drop_index(
        "ix_platform_password_reset_tokens_expires_at",
        table_name="platform_password_reset_tokens",
    )
    op.drop_table("platform_password_reset_tokens")
    op.drop_index(
        "ix_platform_email_verification_tokens_platform_user_id",
        table_name="platform_email_verification_tokens",
    )
    op.drop_index(
        "ix_platform_email_verification_tokens_expires_at",
        table_name="platform_email_verification_tokens",
    )
    op.drop_table("platform_email_verification_tokens")
    op.drop_index(
        "ix_platform_auth_events_platform_user_id", table_name="platform_auth_events"
    )
    op.drop_index(
        "ix_platform_auth_events_event_type", table_name="platform_auth_events"
    )
    op.drop_index(
        "ix_platform_auth_events_created_at", table_name="platform_auth_events"
    )
    op.drop_table("platform_auth_events")
    # ### end Alembic commands ###
